---
title: "How I created This Blog"
description: |
  A short description of the post.
author:
  - name: Tim Sheehan
    url: https://www.linkedin.com/in/timothy-sheehan-20551547/
date: 2023-06-17
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

The links below are what i followed to build this blog. I'm not going to lie to you. This was hard to create, but I learned a lot in the process. In order to get this website launched, I had to learn the distill package, GIT / Github work flows and some basic web design. The beauty is that now that I finally have this site setup and working, now i can truly begin to learn and show my skills.


A big benefit to using R Markdown and Distill is keeping your cost low. So far my only cost has been buying the domain name.

<https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/>
<https://www.youtube.com/watch?v=ZOBXGxPH3Zo>

Cheat Sheets <br>
*R Markdown <br>
  +<https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet>
  +<https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf>
*HTML <br>
  +<https://web.stanford.edu/group/csp/cs21/htmlcheatsheet.pdf>
  +<https://htmlcheatsheet.com/>

Distill is a publication format for scientific and technical writing, native to the web.
Learn more about using Distill at https://rstudio.github.io/distill.
